### ISSUE TITLE
TODO development branch

### ISSUE THREAD

**Issue by alexanderfache6** [alexanderfache6/raspberry-pi-home#1]
- [x] Plot all together in time.
- [x] Look at Database functions to keep track of number of data points, sort by timestamp.
- [ ]  Add humidity, sound, temperature sensors to board.

**Comment by alexanderfache6** [comment]
- [ ] Plot all together in time.

**Comment by alexanderfache6** [comment]
- [ ] Create JSON file to hold all of the data settings separate.

**Comment by alexanderfache6** [comment]
- Created functions to lower case a message to test, functions to update the number of data points and reset num_data_points if it is deleted.

**Comment by alexanderfache6** [comment]
- [ ] Authentication for data access.

**Comment by alexanderfache6** [comment]
LATER:
- [ ] Display data along side "alarm-newsfeed" branch information.
