### ISSUE TITLE
TODO as August 4 end of day commit

### ISSUE THREAD

**Issue by alexanderfache6** [alexanderfache6/raspberry-pi-home#2]
- [ ] Look into Calendar code: 1. Trigger when specific event occurs, 2. Start/stop recording sensor data, 3. Hook up speaker upon data collection / end of event occurrence. New branch

**Comment by alexanderfache6** [comment]
- [ ] having trouble playing mp3 and wav files.
- [ ] Simple UI to display all information.

**Comment by alexanderfache6** [comment]
- [ ] Google Text-to-Speech API integration.

**Comment by alexanderfache6** [comment]
LATER:
- [ ] Integrate with sensor data retrieved from "development" branch and plot along side alarm GUI.
